### ISSUE TITLE
Support high score wins scoring

### ISSUE THREAD

**Issue by tctree333** [Duosmium/sciolyff#1]
Certain tournaments use a "high score wins" scoring method, where first place gets a score of n, 2nd gets n-1, 3rd gets n-2, etc. See the [1999 National Tournament](https://web.archive.org/web/20020110064436/http://nso99.uchicago.edu/crdivcs.html) or [2015 Massachusetts States](https://scioly.org/wiki/images/5/56/2015_MA_B_Results.pdf) for examples.

**Things to consider/assumptions:**
- There's not really an NS/DQ/PO distinction, they're all just 1 or 0 points.
- No drops.
- No penalties.
- All 1st place scores will be the same across events.
  - No max place

**Proposed format change:**
```yaml
Tournament:
  name: Legitimate Tournament Name
  # ...

  # the next line is optional if false (not using pre-2000-style high score wins scoring)
  reverse scoring: true 
```
