### ISSUE TITLE
Support explicit placements

### ISSUE THREAD

**Issue by tctree333** [Duosmium/sciolyff#2]
Some tournaments have unconventional scoring methods that are incompatible with SciolyFF's assumptions. For example, Washington NW Regionals C has a different base `n` for NS vs DQ, and 2 different DQ types.
![image](https://user-images.githubusercontent.com/32943907/157999103-7ec8da96-3929-4ef6-9726-0d89566013c0.png)

It would be nice if we could keep the DQ marking, but manually override the placement instead of computing based on `n + 2`. Non flagged placements could also be marked as "explicit" to avoid a `maxPlace` cap.

**Proposed format change:**
```yaml
Placings:
  - event: Anatomy and Physiology
    team: 58
    # ...

    # this disables place calculations and uses `place` as the score
    explicit: false
```

This flag will not work with raw scores.
